app = ""

kill_signal = "SIGINT"
kill_timeout = 5
# processes = []

[env]
DENO_ENV = "production"
NODE_ENV = "production"
CLOUD_PLATFORM = "fly"
LOG_LEVEL = "info"
CF_BLOCKLIST_URL = "https://dist.rethinkdns.com/blocklists/"
CF_LATEST_BLOCKLIST_TIMESTAMP = "1660227070988"
TD_NODE_COUNT = "45033163"
TD_PARTS = "2"
CF_DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
CF_BLOCKLIST_DOWNLOAD_TIMEOUT = "10000"
# DOT_HAS_PROXY_PROTO = "true"

[experimental]
allowed_public_ports = []
auto_rollback = true

# Don't use `[processes]`, undocumented and causes problems with [auto]scaling.
# Instead, use CMD in Dockerfile.
# [processes]
# app = "run --allow-net --allow-env --import-map=import_map.json server-deno.ts"
# app = "node server-node.js"

# DNS over HTTP[S]
[[services]]
http_checks = []
internal_port = 8080
# processes = ["app"]
protocol = "tcp"
script_checks = []

  [services.concurrency]
  hard_limit = 75
  soft_limit = 60
  type = "connections"

  [[services.ports]]
  # handlers = ["proxy_proto"]
  port = 443

  [[services.tcp_checks]]
  # account for delay due to blocklists download that
  # happens on process startup: plugin.js:systemReady
  grace_period = "15s"
  interval = "30s"
  restart_limit = 6
  timeout = "2s"

# DNS over TCP/TLS
[[services]]
http_checks = []
internal_port = 10000
# processes = ["app"]
protocol = "tcp"
script_checks = []

  [services.concurrency]
  hard_limit = 75
  soft_limit = 60
  type = "connections"

  [[services.ports]]
  # handlers = ["proxy_proto"]
  port = 853

  [[services.tcp_checks]]
  # account for delay due to blocklists download that
  # happens on process startup: plugin.js:systemReady
  grace_period = "15s"
  interval = "30s"
  restart_limit = 6
  timeout = "2s"
