name = "serverless-dns"
route = ""
main = "./dist/worker.js"
account_id = ""
workers_dev = true
# use node_compat or custom build
# node_compat = true
compatibility_date = "2022-11-30"

[build]
command = "npm install && npx webpack"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[vars]
RUNTIME = "worker"
LOG_LEVEL = "debug"
WORKER_ENV = "development"
CLOUD_PLATFORM = "cloudflare"
WORKER_TIMEOUT = 10000
CF_BLOCKLIST_DOWNLOAD_TIMEOUT = 5000
CF_BLOCKLIST_URL = "https://cf.rethinkdns.com/blocklists/"
CF_DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
CF_DNS_RESOLVER_URL_2 = "https://dns.google/dns-query"
CF_LATEST_BLOCKLIST_TIMESTAMP = "1662384683026"
CACHE_TTL = 1800
TD_NODE_COUNT = 42272846
TD_PARTS = 2

##################
#------PROD------#
##################
# wrangler doesn't yet support Workers Services and the new "Environments"
# github.com/cloudflare/cloudflare-docs/pull/3175/files
# github.com/cloudflare/wrangler2/issues/27
# developers.cloudflare.com/workers/platform/environments
[env.prod]
name = "basic-unbound"
routes = [
  "sky.rethinkdns.com/*",
  "sky.bravedns.com/*",
  "basic.rethinkdns.com/*",
  "basic.bravedns.com/*",
]
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
RUNTIME = "worker"
LOG_LEVEL = "info"
WORKER_ENV = "production"
CLOUD_PLATFORM = "cloudflare"
WORKER_TIMEOUT = 10000
CF_BLOCKLIST_DOWNLOAD_TIMEOUT = 5000
CF_BLOCKLIST_URL = "https://cf.rethinkdns.com/blocklists/"
CF_DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
CF_DNS_RESOLVER_URL_2 = "https://dns.google/dns-query"
CF_LATEST_BLOCKLIST_TIMESTAMP = "1662384683026"
CACHE_TTL = 1800
TD_NODE_COUNT = 42272846
TD_PARTS = 2

##################
#-----SECRETS----#
##################
# only for documentation purposes
# developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# [secrets]
# GW_IP4 = ""
# GW_IP6 = ""
