name: PR

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint-fmt:
    name: Lint & fmt
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: ðŸ”§ Run eslint
        run: |
          npm install
          BASE_COMMIT=$(git rev-parse ${{ github.base_ref }})
          HEAD_COMMIT=$(git rev-parse ${{ github.head_ref }})
          npx eslint $( \
            git diff --name-only --diff-filter=ACMRT \
            $BASE_COMMIT...$HEAD_COMMIT \
            ) --cache --fix

      - name: ðŸ‘€ Looking for changes
        id: lint-changes
        run: |
          echo ::set-output name=changes::$( \
            if git diff-index --quiet HEAD --; \
            then echo "false"; \
            else echo "true"; \
            fi)

      - name: ðŸš¢ Pushing to PR branch
        if: steps.lint-changes.outputs.changes == 'true'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --no-verify -am "Automatic lint & fmt"
          git push
